project_id = "rummy500-local"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public", "rummy500"]
extra_search_path = ["public", "extensions", "rummy500"]

[functions.start-game]
verify_jwt = false

[functions.play-meld]
verify_jwt = false

[functions.play-layoff]
verify_jwt = false

[functions.draw-discard]
verify_jwt = false

[functions.replace-joker]
verify_jwt = false
