-- Placeholder for a migration that already exists in the shared remote Supabase project.
-- This repository does not own the original SQL for version 20260204130000.
-- Keep this file so Supabase CLI can align local and remote migration histories safely.
